language: en
pipeline:
  - name: WhitespaceTokenizer
    case_sensitive: false
  - name: RegexFeaturizer
  - name: DucklingHTTPExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.8
    core_threshold: 0.45
    fallback_core_action_name: action_default_fallback
    fallback_nlu_action_name: action_default_fallback
    deny_suggestion_intent_name: out_of_scope
  - name: FormPolicy

